---
- name:            configure /etc/hosts
  lineinfile:
    dest:          /etc/hosts
    line:          "{{ hostvars[item].ansible_host }}  {{ hostvars[item].inventory_hostname }}"
    state:         present
  with_items:
    - dbserver
  tags:            [ 'configure' ]

- name:            Install Tools
  apt:
    force_apt_get: yes
    name:
      - python-mysqldb
    state:         present
  tags:            [ 'packages' ]

- name:            Install mysql-server
  apt:
    force_apt_get: yes
    name:          mysql-server
    state:         present
  tags:            [ 'packages' ]

- name:            ensure mysql listening on all ports
  lineinfile:
    dest:          /etc/mysql/my.cnf
    regexp:        ^bind-address
    line:          "bind-address = 0.0.0.0"
  notify:          restart mysql
  tags:            [ 'configure' ]

- name:            ensure mysql started
  service:
    name:          mysql
    state:         started
    enabled:       yes
  tags:            [ 'services' ]

- name:            create demo database
  mysql_db:
    name:          "{{ db_name }}"
    state:         present
  tags:            [ 'configure' ]

- name:            create demo user
  mysql_user:
    name:          "{{ db_user_name }}"
    password:      "{{ db_user_pass }}"
    priv:          "{{ db_name }}.*:ALL"
    host:          "{{ db_user_host }}"
    state:         present
  tags:            [ 'configure' ]
