---
- name:            configure /etc/hosts
  lineinfile:
    dest:          /etc/hosts
    line:          "{{ hostvars[item].ansible_host }}  {{ hostvars[item].inventory_hostname }}"
    state:         present
  with_items:
    - loadbalancer

- name:            Install Tools
  apt:
    force_apt_get: yes
    name:
      - python-httplib2
    state:         present
    update_cache:  yes

- name:            Install nginx
  apt:
    force_apt_get: yes
    name:          nginx
    state:         present
    update_cache:  yes

- name:            configure nginx site
  template:
    src:           nginx.conf.j2
    dest:          /etc/nginx/sites-available/demo
    mode:          0644
  notify:          restart nginx
- wait_for:        port=80

- name:            deactivate default nginx sites-available
  file:
    path:          /etc/nginx/sites-enabled/default
    state:         absent
  notify:          restart nginx
- wait_for:        port=80

- name:            activate demo nginx site
  file:
    src:           /etc/nginx/sites-available/demo
    dest:          /etc/nginx/sites-enabled/demo
    state:         link
  notify:          restart nginx

- name:            ensure nginx started
  service:
    name:          nginx
    state:         started
    enabled:       yes
