---
- name:            configure /etc/hosts
  lineinfile:
    dest:          /etc/hosts
    line:          "{{ hostvars[item].ansible_host }}  {{ hostvars[item].inventory_hostname }}"
    state:         present
  with_items:
    - loadbalancer
  tags:            [ 'configure' ]

- name:            Install Tools
  apt:
    force_apt_get: yes
    name:
      - python-httplib2
    state:         present
  tags:            [ 'packages' ]

- name:            Install nginx
  apt:
    force_apt_get: yes
    name:          nginx
    state:         present
  tags:            [ 'packages' ]

# - name:          debug
#   debug:
#     msg:         "{{ sites }}"
#   tags:          [ 'configure' ]

- name:            configure nginx site
  template:
    src:           nginx.conf.j2
    dest:          /etc/nginx/sites-available/{{ item.key }}
    mode:          0644
  with_dict:       "{{ sites }}"
  notify:          restart nginx
  tags:            [ 'configure' ]

- name:            get active sites
  shell:           ls -1 /etc/nginx/sites-enabled
  register:        active
  changed_when:    "active.stdout_lines != sites.keys()"
  tags:            [ 'configure' ]

- name:            de-activate sites
  file:
    path:          /etc/nginx/sites-enabled/{{ item }}
    state:         absent
  with_items:      active.stdout_lines
  when:            item not in {{ sites }}
  notify:          restart nginx
- wait_for:        port=80

- name:            activate demo nginx site
  file:
    src:           /etc/nginx/sites-available/{{ item.key }}
    dest:          /etc/nginx/sites-enabled/{{ item.key }}
    state:         link
  with_dict:       "{{ sites }}"
  notify:          restart nginx

- name:            ensure nginx started
  service:
    name:          nginx
    state:         started
    enabled:       yes
