---
 - hosts:          all
   become:         true
   tasks:
     - name:       configure /etc/hosts
       lineinfile:
         dest:     /etc/hosts
         line:     "{{ hostvars[item].ansible_host }}  {{ hostvars[item].inventory_hostname }}"
         state:    present
       with_items:
         - loadbalancer
         - webserver
         - dbserver
